# Generated by Django 4.2.3 on 2023-07-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todomodel',
            name='status',
        ),
        migrations.AddField(
            model_name='todomodel',
            name='is_complete',
            field=models.BooleanField(default=False, verbose_name='Завершено'),
        ),
    ]
